name: docker image workflow
on: push
jobs:
  build:
    name: build-push docker image
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code base
      uses: actions/checkout@v1
    
    - name: docker build action
      id: buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_UNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
        
    - name: build and push to dockerhub
      uses: docker/build-push-action@v2
      with:
        contex: .
        tags: |
          siddhjain66/react_news:1.0
        push: ${{github.ref =='refs/heads/master'}}
      env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
