name: Super-Linter
on:
  push:
    branches: [main,master]
  pull_request:
    branches: [main,master]
jobs:
  super-lint:
    name: Lint code 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Run super-linter
        uses: github/super-linter@v4       
       
#       - run: standard --fix
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
